### ISSUE TITLE
Profile page looks weird if user's data in the database is malformed

### ISSUE THREAD

**Issue by andreastedile** [carlocorradini/graphmarket#187]
Suppose the database contains data with a wrong format, for example a phone number in a wrong format.
```
+003834018638346
```
When logging into Graph Market's website, we are greeted by the following page:
![image](https://user-images.githubusercontent.com/39307731/107282476-4eb53a00-6a5b-11eb-8698-2a2052b78140.png)
(Notice how the user's profile is empty).
This is a corner case, but it should be fixed in subsequent versions...

**Comment by carlocorradini** [comment]
Purtroppo il database e' solo un contenitore -> non se quanto sia efficace/efficiente avere un regex come check. Il controllo e' dato sia in input che output da graphQL proprio per avere una sicurezza del 100%.

**Comment by andreastedile** [comment]
Esatto. Forse in futuro Typeorm o simili dovrebbbero controllare i dati caricati o simili, comunque per ora va bene così
